import{a as E,S as T,i as a}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const B="43804338-e495c959d27dd2a0f1faf63f4",S="https://pixabay.com/api/";async function m(o,r){try{return(await E.get(S,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}})).data}catch(e){throw console.error("Error fetching data, please try again:",e),e}}function u(o,r){const e=document.querySelector(".gallery"),d=o.map(({webformatURL:t,largeImageURL:s,tags:i,likes:b,views:w,comments:L,downloads:v})=>`<li class="gallery-item">
            <a href = "${s}">
        <img src="${t}" alt="${i}"/>
    <ul class="gallery-info">
        <li>Likes<p>${b}</p></li>
        <li>Views<p>${w}</p></li>
        <li>Comments<p>${L}</p></li>
        <li>Downloads<p>${v}</p></li>
    </ul>
    </a>
    </li>`).join("");e.insertAdjacentHTML("beforeend",d),r.refresh()}const q={captionsData:"alt",captionDelay:250};let y=new T(".gallery a",q);const I=document.querySelector(".search-form"),h=document.querySelector(".search-images"),c=document.querySelector(".loader"),l=document.querySelector(".load-more-button"),P=document.querySelector(".gallery"),O=document.getElementById("scrollToTopBtn");let n=1,g="",f=[],p=0;document.addEventListener("DOMContentLoaded",()=>{l.style.display="none",O.style.display="none"});I.addEventListener("submit",async function(o){o.preventDefault();const r=h.value.trim();if(c.style.display="block",l.style.display="none",P.innerHTML="",n=1,r===""){a.error({message:"Please enter a search term!",position:"topRight"}),c.style.display="none";return}try{const e=await m(r,n);e.hits.length===0?(u([]),l.style.display="none",a.error({title:"Error!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})):(u(e.hits,y),y.refresh(),l.style.display="block",g=r,f=e.hits,p=Math.ceil(e.totalHits/e.hits.length),e.totalHits<=e.hits.length?l.style.display="none":l.style.display="block")}catch(e){console.error("Error fetching images:",e),a.error({title:"Error!",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{c.style.display="none",f.length>0&&n<p&&(l.style.display="block")}h.value=""});l.addEventListener("click",async()=>{if(n>=p){l.style.display="none",a.info({message:"You've reached the end of search results.",position:"topRight"});return}try{c.style.display="block",l.style.display="none";const o=await m(g,++n);if(o.hits.length===0)l.style.display="none",a.info({message:"You've reached the end of search results.",position:"topRight"});else{u(o.hits,y);const r=document.querySelector(".gallery-item");y.refresh();const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),n>=p&&(l.style.display="none")}}catch(o){console.log(o)}finally{c.style.display="none"}});window.addEventListener("scroll",()=>{const o=document.getElementById("scrollToTopBtn");window.scrollY>300?o.style.display="block":o.style.display="none"});document.getElementById("scrollToTopBtn").addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
