import{a as v,S as E,i}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const S="43804338-e495c959d27dd2a0f1faf63f4",T="https://pixabay.com/api/";async function f(o,r){try{return(await v.get(T,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15}})).data}catch(e){throw console.error("Error fetching data, please try again:",e),e}}function p(o,r){const e=document.querySelector(".gallery"),d=o.map(({webformatURL:t,largeImageURL:s,tags:l,likes:g,views:w,comments:b,downloads:L})=>`<li class="gallery-item">
            <a href = "${s}">
        <img src="${t}" alt="${l}"/>
    <ul class="gallery-info">
        <li>Likes<p>${g}</p></li>
        <li>Views<p>${w}</p></li>
        <li>Comments<p>${b}</p></li>
        <li>Downloads<p>${L}</p></li>
    </ul>
    </a>
    </li>`).join("");e.insertAdjacentHTML("beforeend",d),r.refresh()}const q={captionsData:"alt",captionDelay:250};let y=new E(".gallery a",q);const P=document.querySelector(".search-form"),h=document.querySelector(".search-images"),a=document.querySelector(".loader"),n=document.querySelector(".load-more-button"),B=document.querySelector(".gallery");let c=1,m="",I=[],u=0;document.addEventListener("DOMContentLoaded",()=>{n.style.display="none"});P.addEventListener("submit",async function(o){o.preventDefault();const r=h.value.trim();if(a.style.display="block",B.innerHTML="",c=1,r===""){i.error({message:"Please enter a search term!",position:"topRight"}),a.style.display="none";return}try{const e=await f(r,c);e.hits.length===0?(p([]),n.style.display="none",i.error({title:"Error!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})):(p(e.hits,y),y.refresh(),n.style.display="block",m=r,I=e.hits,u=Math.ceil(e.totalHits/e.hits.length),e.totalHits<=e.hits.length?n.style.display="none":n.style.display="block")}catch(e){console.error("Error fetching images:",e),i.error({title:"Error!",message:"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{a.style.display="none"}h.value=""});n.addEventListener("click",async()=>{if(c>=u){n.style.display="none",i.info({message:"You've reached the end of search results.",position:"topRight"});return}try{a.style.display="block";const o=await f(m,++c);if(o.hits.length===0)n.style.display="none",i.info({message:"You've reached the end of search results.",position:"topRight"});else{p(o.hits,y);const r=document.querySelector(".gallery a");y.refresh();const e=r.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),c>=u&&(n.style.display="none")}}catch(o){console.log(o)}finally{a.style.display="none"}});window.addEventListener("scroll",()=>{const o=document.getElementById("scrollToTopBtn");window.scrollY>300?o.style.display="block":o.style.display="none"});document.getElementById("scrollToTopBtn").addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
