import{a as E,S as T,i as a}from"./assets/vendor-6e0bf343.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const l of t)if(l.type==="childList")for(const i of l.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&y(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const l={};return t.integrity&&(l.integrity=t.integrity),t.referrerPolicy&&(l.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?l.credentials="include":t.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function y(t){if(t.ep)return;t.ep=!0;const l=e(t);fetch(t.href,l)}})();const B="43804338-e495c959d27dd2a0f1faf63f4",S="https://pixabay.com/api/";async function m(r,s){try{return(await E.get(S,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:15}})).data}catch(e){throw console.error("Error fetching data, please try again:",e),e}}function u(r,s){const e=document.querySelector(".gallery"),y=r.map(({webformatURL:t,largeImageURL:l,tags:i,likes:b,views:w,comments:L,downloads:v})=>`<li class="gallery-item">
            <a href = "${l}">
        <img src="${t}" alt="${i}"/>
    <ul class="gallery-info">
        <li>Likes<p>${b}</p></li>
        <li>Views<p>${w}</p></li>
        <li>Comments<p>${L}</p></li>
        <li>Downloads<p>${v}</p></li>
    </ul>
    </a>
    </li>`).join("");e.insertAdjacentHTML("beforeend",y),s.refresh()}const q={captionsData:"alt",captionDelay:250};let p=new T(".gallery a",q);const I=document.querySelector(".search-form"),h=document.querySelector(".search-images"),c=document.querySelector(".loader"),o=document.querySelector(".load-more-button"),P=document.querySelector(".gallery"),O=document.getElementById("scrollToTopBtn");let n=1,g="",f=[],d=0;document.addEventListener("DOMContentLoaded",()=>{o.style.display="none",O.style.display="none"});I.addEventListener("submit",async function(r){r.preventDefault();const s=h.value.trim();if(c.style.display="block",o.style.display="none",P.innerHTML="",n=1,s===""){a.error({message:"Please enter a search term!",position:"topRight"}),c.style.display="none";return}try{const e=await m(s,n);e.hits.length===0?(u([]),o.style.display="none",a.error({title:"Error!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),o.style.display="none"):(u(e.hits,p),p.refresh(),o.style.display="block",g=s,f=e.hits,d=Math.ceil(e.totalHits/e.hits.length),n<d?o.style.display="block":o.style.display="none")}catch(e){console.error("Error fetching images:",e),a.error({title:"Error!",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),o.style.display="none"}finally{c.style.display="none",f.length>0&&n<d&&(o.style.display="block")}h.value=""});o.addEventListener("click",async()=>{if(n>=d){o.style.display="none",a.info({message:"You've reached the end of search results.",position:"topRight"});return}try{c.style.display="block",o.style.display="none";const r=await m(g,++n);if(r.hits.length===0)o.style.display="none",a.info({message:"You've reached the end of search results.",position:"topRight"}),o.style.display="none";else{u(r.hits,p);const s=document.querySelector(".gallery-item");p.refresh();const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),n>=d&&(o.style.display="none")}}catch(r){console.log(r),o.style.display="none"}finally{c.style.display="none"}});window.addEventListener("scroll",()=>{const r=document.getElementById("scrollToTopBtn");window.scrollY>300?r.style.display="block":r.style.display="none"});document.getElementById("scrollToTopBtn").addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
